feature/about-made-tablet
slavikidak/project-pink pull request #22
Opened 2022-01-28 17:23 UTC by MykolaFurevych

добавив планшетну версію

2022-01-28 18:03 UTC, slavikidak requested changes
Потрібно попрацювати з класами, бо зараз bg-img, логічно робити по БЕМу
Так само з flexbox

2022-01-28 18:03 UTC, Olyazarichna commented on src/sass/layouts/_about.scss
> +  @media screen and (min-width: 768px) and (max-width: 1199px) {
може не треба обмежувати 1199, просто при 1200 перевизначити стилі

2022-01-28 18:09 UTC, Vitaliy28031985 submitted a review, later dismissed

2022-01-28 19:41 UTC, Olyazarichna approved these changes

2022-01-28 19:41 UTC, Olyazarichna submitted a review, later dismissed

2022-01-29 09:28 UTC, slavikidak approved these changes

2022-01-29 09:28 UTC, merged