products
slavikidak/project-pink pull request #24
Opened 2022-01-28 19:05 UTC by Krystyna1012

2022-01-28 19:10 UTC, OleksandrRomanchuk commented on src/partials/products.html
> +<section class="products container">
клас контейнер не може бути на секції, повинен бути "контейнер"

2022-01-28 19:13 UTC, OleksandrRomanchuk commented on src/partials/products.html
> +            <p class="products__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
"кружечки" мають бути псевдоелементами (біфор / афтер)

2022-01-28 19:14 UTC, OleksandrRomanchuk commented on src/partials/products.html
> +            <h3 class="products__product-name">ice coffee<div class="products__more"></div></h3>
"кружечки" мають бути псевдоелементами (біфор / афтер), а не дівом у заголовку

2022-01-28 19:16 UTC, slavikidak requested changes
Додай контейнер

2022-01-28 19:16 UTC, slavikidak commented on src/partials/products.html
> +<section class="products container">
<section>
  <container>
  </container>
</section>

2022-01-28 19:28 UTC, OleksandrRomanchuk requested changes

2022-01-28 19:28 UTC, OleksandrRomanchuk commented on src/partials/products.html
> +</section>
Було дуже-дуже непогано, якщо б одразу додала кругленьку кнопочку зі срілочкою у кожній картці

2022-01-28 19:28 UTC, OleksandrRomanchuk commented on src/sass/layouts/_products.scss
> +  &__more::after {
Задай цей елемент заголовку

2022-01-28 19:28 UTC, OleksandrRomanchuk commented on src/sass/layouts/_products.scss
> +    width: 6px;
це розмір однієї "крапки", а тобі потрібно всього елемента

2022-01-28 19:28 UTC, OleksandrRomanchuk commented on src/sass/layouts/_products.scss
> +    margin-bottom: 49px;
задавай всюди тільки margin-top або margin-bottom - щось одне по всій секції, теж саме з лівим та правим

2022-01-28 19:28 UTC, OleksandrRomanchuk commented on src/sass/layouts/_products.scss
> +  display: flex;
для мобілки немає необхіідності, до того ж ти переносиш і ставиш в колону

2022-01-28 19:28 UTC, OleksandrRomanchuk commented on src/sass/layouts/_products.scss
> +.products {
Ніяких    font-style: normal; та font-weight: normal; немає бути

2022-01-28 19:28 UTC, OleksandrRomanchuk commented on src/sass/layouts/_products.scss
> +    display: flex;
для мобілки не потрібно

2022-01-28 19:28 UTC, OleksandrRomanchuk commented on src/sass/layouts/_products.scss
> +    display: flex;
для мобілки не потрібно

2022-01-28 19:28 UTC, OleksandrRomanchuk commented on src/sass/layouts/_products.scss
> +}
оператор конкатенації (&) використовується тільки для псевдокласів стану (ховер, фокус)

2022-01-28 19:28 UTC, OleksandrRomanchuk commented on src/sass/layouts/_products.scss
> +    margin-bottom: 38px;
він зпозиціонований, на нього марджин не діє

2022-01-30 10:56 UTC, Krystyna1012 reviewed
& ментор коли перевіряла дз зауважень не робила, до цього ж я бачила це десь в коментарях

2022-01-30 11:26 UTC, OleksandrRomanchuk submitted a review, later dismissed

2022-01-30 11:37 UTC, OleksandrRomanchuk approved these changes

2022-01-30 11:39 UTC, merged